### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Nuginu** [Equinox-/runelite-influxdb#1]
I am interested in getting this going, but I cant seem to figure out a way to actually get runel;ite to send metrics to my influx server.

**Comment by Equinox-** [comment]
So this uses the pre-flux InfluxQL API (1.x).

You should have a URL endpoint that the API is hosted under.  By default this would be `http://server-ip:8086`.  This is the server URL, andnis also what gets printed when you run the influx CLI.
Then you'll need a database on the influx server using some admin credentials and likely create a second user for use with reporting. (https://docs.influxdata.com/influxdb/v1.8/introduction/get-started/ covers database creation)

Once you have the server URL, database name, and a influx username and password you just fill those into the config and it should send the next XP change.  Visualizing the data it stores is up to you.

**Comment by Nuginu** [comment]
> So this uses the pre-flux InfluxQL API (1.x).
> You should have a URL endpoint that the API is hosted under.  By default this would be http://server-ip:8086.  This is the server URL, andnis also what gets printed when you run the influx CLI.
> Then you'll need a database on the influx server using some admin credentials and likely create a second user for use with reporting. (https://docs.influxdata.com/influxdb/v1.8/introduction/get-started/ covers database creation)
> Once you have the server URL, database name, and a influx username and password you just fill those into the config and it should send the next XP change.  Visualizing the data it stores is up to you.

I have the server starting, but I don't seem to understand how to query the server to see if it's even receiving data. is there a gui that could be accesed for this?

**Comment by Equinox-** [comment]
InfluxDB is a database only.  To visualize the data you would need to use a separate tool, like Grafana or Chronograf.

This plugin is primarily aimed at people who are already running InfluxDB for some other reason, since it's not really practical to run an entire database and UI just for a single RS character.
