### ISSUE TITLE
Share importable dashboard

### ISSUE THREAD

**Issue by niekcandaele** [Equinox-/runelite-influxdb#10]
Hello, thanks for a great plugin!

Instead of a snapshot, could you export your Grafana dashboard (possibly upload to https://grafana.com/grafana/dashboards)? An importable example would help people to install this and get started quicker.

You'd make my life a lot easier :smile:

**Comment by Equinox-** [comment]
https://github.com/Equinox-/runelite-influxdb/blob/master/example-dashboard.json should work for you.

**Comment by niekcandaele** [comment]
Much appreciated!
