### ISSUE TITLE
Grafana

### ISSUE THREAD

**Issue by vyrealt** [Equinox-/runelite-influxdb#12]
did import your example grafana but just wondering is it possible make query to display  total xp/h  across 2 or more users and if its possible mind giving me example how to do it.

**Comment by Equinox-** [comment]
`SELECT sum(derivative) FROM (SELECT derivative(last("xp"), 1h) FROM "rs_skill" WHERE ("skill" = 'OVERALL') AND $timeFilter GROUP BY time(10m), "user" fill(previous)) GROUP BY time(10m)`
https://archive.docs.influxdata.com/influxdb/v1.2/query_language/data_exploration/#subqueries
https://grafana.com/docs/grafana/latest/datasources/influxdb/#text-editor-mode-raw
