### ISSUE TITLE
Breaking plugin-hub changes

### ISSUE THREAD

**Issue by abextm** [Equinox-/runelite-influxdb#13]
As of runelite/plugin-hub#725 this plugin will no longer build due to [this line](https://github.com/Equinox-/runelite-influxdb/blob/master/build.gradle.kts#L64) in your build script. We will start to enforce a maximum line length of roughly 100 characters on all build files to make it more difficult to hide malicious plugins.

**Comment by Equinox-** [comment]
https://github.com/runelite/plugin-hub/pull/726
