### ISSUE TITLE
Image previews

### ISSUE THREAD

**Issue by thebubbsy** [Equinox-/runelite-influxdb#2]
Hey can we get a few images that preview of your Chronograf dashboard to show what benefit this is and the way it can show the data thats collected. for general xp tracking - if theres a benefit over temple tracking. item tracking, eg coins or herbs.
Login time tracked could be cool too.

Thanks

**Comment by Equinox-** [comment]
Added a snapshot of my Grafana dashboard: https://snapshot.raintank.io/dashboard/snapshot/GfthlH9m4xT5FwX6V919RXaHTSuUD3Xi?orgId=2

The main reason for this plugin is to gather long term stats about an account, something that the existing runelite tools doesn't really do a great job with.  Plus I was already running the influxdb server/grafana server so thought "why not"

**Comment by thebubbsy** [comment]
thats beast, thanks mate
