### ISSUE TITLE
Submit all boss kc on plugin startup

### ISSUE THREAD

**Issue by hjdarnel** [Equinox-/runelite-influxdb#4]
I think it would be helpful if the plugin submitted all of my boss KC on startup, or when visiting the collection log, or something similar, instead of just on a boss kill. Just like how all skill xp is reported without needing to gain XP first! I'm not sure if the chat commands plugin has an easy way to access that, but you'd have to change some of the logic here https://github.com/Equinox-/runelite-influxdb/blob/master/src/main/java/net/machpi/runelite/influxdb/InfluxDbPlugin.java#L122-L135

**Comment by hjdarnel** [comment]
As I'm building out some Grafana dashboards, another way would be to report when the chat command is used. Again I'm not sure of any hooks that we could tie into this, but if it's easier it's certainly doable to just `!kc boss` to populate some numbers initially. I realize this data logging is best for showing increases over time and not "current stats"" though.

**Comment by Equinox-** [comment]
I can easily report the current state from the same place I receive updates on plugin load.  Already have it working, just have to push it up.

**Comment by Equinox-** [comment]
I have some more work I want to do before I push changes up to the plugin hub, so the most recent changes won't show up there immediately.
