### ISSUE TITLE
Quantity of items?

### ISSUE THREAD

**Issue by Zumzod** [Equinox-/runelite-influxdb#8]
Love the plugin!
Is it possible to add the quantity of items?

As an ironman and hoarder it would be interesting to be able to make graphs of that.
Would make it possible to make more advanced Banked XP trackers and for example see how much supplies/xp you get from slayer, herbiboar etc

**Comment by Equinox-** [comment]
So by design this plugin only tracks stacks valued at more than 50k in your bank to keep the number of fields fairly low.  I can easily add a quantity series for these items (in fact it appears I was planning to already) but tracking the number for every item is a bit impractical.

**Comment by Zumzod** [comment]
> 
> 
> So by design this plugin only tracks stacks valued at more than 50k in your bank to keep the number of fields fairly low. I can easily add a quantity series for these items (in fact it appears I was planning to already) but tracking the number for every item is a bit impractical.

Sounds like a good plan!
Value of 50k seems like a good cut-off point.
